### PR TITLE
Update Licence

### PR DESCRIPTION
**Pull request by DanPurdy**
Updates the licence URL now that echo base is public

### CODE REVIEW

**Comment by DanPurdy** [comment]
Odd that the tests are failing here without any changes..

**Comment by DanPurdy** [comment]
We may need to look at the tests again here, seems a dependancy has updated and removed our ability to test scss properly..

**Comment by DanPurdy** [comment]
Good to merge

**Comment by bgriffith** [comment]
Do we want to target the license on develop?

**Comment by DanPurdy** [comment]
Seen as it's our default branch I think we should

**Pull request merged**
